# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Metalama
email: hello@postsharp.net
description: > # this means to ignore newlines until "baseurl:"
  Announcements, opinions, tips and tricks from PostSharp Technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://metalama.net" # the base hostname & protocol for your site
twitter_username: postsharp
github_username:  postsharp
facebook_username: postsharp
linkedin_username: postsharp

main_website_url: https://metalama.net

strict_front_matter: true

title_separator: "|"

#excerpt_separator: "<!-- readmore -->"

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-toc
# - jekyll-last-modified-at
  
exclude: ["*.ps1", "README.md"]
include: ["solutions/*.md"]

sass:
  style: compressed
  sourcemap: always
  silence_deprecations: ["import", "slash-div"]


defaults: 
  - scope:
      path: "" 
      type: "pages" 
    values:
      layout: "plain" 
      site_title: "Metalama"
  - scope:
      path: "solutions" 
      type: "pages" 
    values:
      layout: "structured"       
      toc: true
      site_title: "Metalama Applications"
  - scope:
      path: "contributing" 
      type: "pages" 
    values:
      layout: "structured"       
      toc: true
  - scope:
      path: "support" 
      type: "pages" 
    values:
      layout: "structured"       
      toc: true
      
toc:
  min_level: 2
  max_level: 2

markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false
  